apiVersion: v1
entries:
  rancher:
  - apiVersion: v1
    appVersion: 2.6.3-freeipa
    created: "2022-02-07T12:22:03.085844+04:00"
    description: Install Rancher Server to manage Kubernetes clusters across providers.
    digest: ed6050c5c870b35ee3279e628e524ce2a4c50b4fa4db164e74df6ec1c462219d
    home: https://rancher.com
    icon: https://github.com/rancher/ui/blob/master/public/assets/images/logos/welcome-cow.svg
    keywords:
    - rancher
    kubeVersion: < 1.23.0-0
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: rancher
    sources:
    - https://github.com/rancher/rancher
    - https://github.com/rancher/server-chart
    urls:
    - rancher-2.6.3-freeipa.tgz
    version: 2.6.3-freeipa
generated: "2022-02-07T12:22:03.084685+04:00"
