#!/usr/bin/env bash

echo "-- chart/validate --"

# Check for helm
if [ -z "$(type -p helm)" ]; then
    echo "helm_v3 not found. Helm is required to run tests."
    exit 1
fi

helm lint ../../build/chart/rancher
